/** Zonas horarias IANA habituales para el selector de tenants */
export const TIMEZONES: { value: string; label: string }[] = [
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires (UTC−3)" },
  { value: "America/Argentina/Cordoba", label: "Córdoba (UTC−3)" },
  { value: "America/Argentina/Mendoza", label: "Mendoza (UTC−3)" },
  { value: "America/Argentina/Salta", label: "Salta (UTC−3)" },
  { value: "America/Argentina/Tucuman", label: "Tucumán (UTC−3)" },
  { value: "America/Argentina/Ushuaia", label: "Ushuaia (UTC−3)" },
  { value: "America/Mexico_City", label: "Ciudad de México (UTC−6)" },
  { value: "America/Monterrey", label: "Monterrey (UTC−6)" },
  { value: "America/Guatemala", label: "Guatemala (UTC−6)" },
  { value: "America/Bogota", label: "Bogotá (UTC−5)" },
  { value: "America/Lima", label: "Lima (UTC−5)" },
  { value: "America/Caracas", label: "Caracas (UTC−4)" },
  { value: "America/Santiago", label: "Santiago (UTC−4/−3)" },
  { value: "America/La_Paz", label: "La Paz (UTC−4)" },
  { value: "America/Sao_Paulo", label: "São Paulo (UTC−3)" },
  { value: "America/Rio_Branco", label: "Rio Branco (UTC−5)" },
  { value: "America/New_York", label: "Nueva York (UTC−5/−4)" },
  { value: "America/Chicago", label: "Chicago (UTC−6/−5)" },
  { value: "America/Denver", label: "Denver (UTC−7/−6)" },
  { value: "America/Los_Angeles", label: "Los Ángeles (UTC−8/−7)" },
  { value: "America/Toronto", label: "Toronto (UTC−5/−4)" },
  { value: "America/Vancouver", label: "Vancouver (UTC−8/−7)" },
  { value: "Europe/Madrid", label: "Madrid (UTC+1/+2)" },
  { value: "Europe/Barcelona", label: "Barcelona (UTC+1/+2)" },
  { value: "Europe/London", label: "Londres (UTC+0/+1)" },
  { value: "Europe/Paris", label: "París (UTC+1/+2)" },
  { value: "Europe/Berlin", label: "Berlín (UTC+1/+2)" },
  { value: "Europe/Rome", label: "Roma (UTC+1/+2)" },
  { value: "Europe/Moscow", label: "Moscú (UTC+3)" },
  { value: "UTC", label: "UTC" },
];
